spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: servicio-producto
            uri: lb://servicio-producto
            predicates:
              - Path=/v2/**
            filters:
              - StripPrefix=1
          - id: servicio-item
            uri: lb://servicio-item
            predicates:
              - Path=/v2/**
            filters:
              - StripPrefix=1
